version: '3.5'
services:
  database:
    image: mysql:5.6
    container_name: movie-api
    volumes:
      - ./db:/var/tmp/scripts
    ports:
      - 8989:8080
    environment:
      - DB_SID=movie-api
